# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Amp demo for disqus
email: adam@northisup.com
description: > # this means to ignore newlines until "baseurl:"
  Musings on not much. Mainly used as a testing ground for disqus.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://northisup.com" # the base hostname & protocol for your site
permalink: '/:title/'

# Build settings
markdown: kramdown
exclude:
  - vendor

sass:
  sass_dir: _sass

disqus:
  shortname: northisup

# gems:
  # - jekyll-embedly-plugin
  # - jekyll-mentions
  # - jemoji
  # - jekyll-redirect-from
  # - jekyll-sitemap
  # - jekyll-feed
